WIP - more debug

diff --git a/.github/workflows/sdk.yaml b/.github/workflows/sdk.yaml
--- a/.github/workflows/sdk.yaml
+++ b/.github/workflows/sdk.yaml
@@ -249,6 +249,7 @@ jobs:
             /^\-version/ { old = v($2) }
             END {
                 if (new == "" || old == "") {
+                  printf("cannot find version diff\n")
                   exit 1
                 }
                 split(old, a, ".")
@@ -267,7 +268,8 @@ jobs:
           _EOF_
           for name in "${dirs[@]}"; do
             echo DEBUG name = $name
-            git diff origin/main..HEAD -- "${name}/Cargo.toml" | awk -F' = ' -f major-break.awk || true
+            git diff origin/main..HEAD -- "${name}/Cargo.toml" | awk -F' = ' -f major-break.awk
+            echo DEBUG === $?
             if git diff origin/main..HEAD -- "${name}/Cargo.toml" | awk -F' = ' -f major-break.awk; then
               echo DEBUG name mismatched = $name
               cat <<_EOF_
